linters:
  disable-all: true
  enable:
    - errcheck
    - gocritic
    - govet
    - nonamedreturns
    - staticcheck
    - revive
    - wrapcheck
  presets:
    - unused

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # Ignore
  staticcheck:
    checks:
      - "-SA3000"
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - appendCombine
      - appendAssign
      - commentFormatting
      - ifElseChain
      - singleCaseSwitch
  wrapcheck:
    ignoreSigs:
      # all go error pkg related signatures
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
      # our own error signatures
      - .WrapIncorrectUsageError(
      - .WrapCouldBeSandboxError(
      - .WrapExecError(
      - .WrapSilentError
      # only check external packages
      - code-intelligence.com
      # context doesn't really need to be wrapped/have a stack trace
      - context.Context
    ignorePackageGlobs:
      # ignoring test packages because we check for errors and don't need to wrap them
      - "integration-tests"
      - "e2e-tests"
      - "internal/testutil"

run:
  timeout: 3m
