name: "Run cifuzz examples"
description: "running examples with previously installed cifuzz"
inputs:
  os:
    description: "current vm operating system"
    required: true
runs:
  using: "composite"
  steps:
    - name: Run CMake Example
      run: |
        cd examples/cmake
        cifuzz run my_fuzz_test 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "heap buffer overflow"
        cat fuzzing.log | grep "undefined behavior"
        cat fuzzing.log | grep -E "Findings:\s+2"
      shell: bash

    - name: Run CMake Example in Container
      if: contains(inputs.os, 'ubuntu') || contains(inputs.os, 'arch')
      run: |
        make build-container-image
        cd examples/cmake
        DOCKER_BUILDKIT=1 docker build -t cmake-runner .
        CIFUZZ_PRERELEASE=1 cifuzz container run -v --docker-image cmake-runner my_fuzz_test 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "heap buffer overflow"
        cat fuzzing.log | grep "undefined behavior"
      shell: bash

    - name: Run Other Build System Example
      if: contains(inputs.os, 'macos') || contains(inputs.os, 'ubuntu') || contains(inputs.os, 'arch')
      run: |
        cd examples/other
        cifuzz run my_fuzz_test 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "heap buffer overflow"
        cat fuzzing.log | grep "undefined behavior"
        cat fuzzing.log | grep -E "Findings:\s+2"
      shell: bash

    - name: Run Bazel Example
      if: contains(inputs.os, 'ubuntu') || contains(inputs.os, 'arch')
      run: |
        cd examples/bazel
        cifuzz run -v src:explore_me_fuzz_test 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "heap buffer overflow"
        cat fuzzing.log | grep "undefined behavior"
        cat fuzzing.log | grep -E "Findings:\s+2"
      shell: bash

    - name: Run Maven Example
      run: |
        cd examples/maven
        cifuzz run com.example.FuzzTestCase 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "Remote Code Execution"
        cat fuzzing.log | grep -E "Findings:\s+1"
      shell: bash

    - name: Run Gradle Example
      run: |
        cd examples/gradle
        cifuzz run com.example.FuzzTestCase 2>&1 | tee fuzzing.log
        cat fuzzing.log | grep "Remote Code Execution"
        cat fuzzing.log | grep -E "Findings:\s+1"
      shell: bash
