name: Test large runners

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  workflow_dispatch:

jobs:
  unit_tests:
    name: unit tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            cifuzz-windows2022-8core,
            windows-2022,
            ubuntu-22.04,
            cifuzz-ubuntu2204-8core,
          ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Run unit tests
        run: make test/unit

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: gotest.log
          if-no-files-found: error

  integration_tests:
    name: integration tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            cifuzz-windows2022-8core,
            windows-2022,
            ubuntu-22.04,
            cifuzz-ubuntu2204-8core,
          ]
        ci_index: [0, 1, 2]
        include:
          - os: cifuzz-windows2022-8core
            ci_index: 3
          - os: cifuzz-windows2022-8core
            ci_index: 4
          - os: cifuzz-windows2022-8core
            ci_index: 5
          - os: windows-2022
            ci_index: 3
          - os: windows-2022
            ci_index: 4
          - os: windows-2022
            ci_index: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup VM for cifuzz
        uses: ./.github/actions/vm_setup
        with:
          os: ${{ matrix.os }}

      - name: Run integration tests
        if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'mac')
        run: make test/integration/linux-mac/${{ matrix.ci_index }}
        shell: bash

      - name: Run integration tests
        if: contains(matrix.os, 'windows')
        run: make test/integration/win/${{ matrix.ci_index }}

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log-${{ matrix.os }}-${{ matrix.ci_index }}
          path: gotest.log
          if-no-files-found: error
