name: Release Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

  installer:
    uses: ./.github/workflows/workflow_installer.yml
    needs: version
    permissions:
      actions: write # for uploading artifacts
    with:
      version: ${{ needs.version.outputs.version }}
      compatibility_check: ${{ vars.RELEASE_COMPATIBILITY_CHECK }}

  create_release:
    name: Create draft release
    runs-on: ubuntu-22.04
    needs: [version, installer]
    permissions:
      contents: write # for creating releases

    steps:
      # needed for the release template
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: cifuzz_installer

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: cifuzz Release ${{ needs.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: ./.github/release_template.md
          generate_release_notes: true
          draft: true
          files: cifuzz_installer_*
          fail_on_unmatched_files: true
